sudo: required
services:
  - docker

before_install: 
  - docker build -t akano-react -f Dockerfile.dev .

script: 
  - docker run -e CI=true akano-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "dev-bstalk-01"
  env: "Dev-bstalk-01-env"
  bucket_name: "elasticbeanstalk-us-east-1-463374320634"
  bucket_path: "dev-bstalk-01"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY" 
  
    
